'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace T227361


	Partial Public Class [Default]

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ddlExportFormat control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ddlExportFormat As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' btExport control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btExport As Global.System.Web.UI.WebControls.Button
	End Class
End Namespace
